/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PaymentFailureRouteImport } from './routes/payment-failure'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedBlogEditorRouteImport } from './routes/_authenticated/blog-editor'
import { Route as AuthenticatedCareerRouteImport } from './routes/_authenticated/career'
import { Route as AuthenticatedCareerCoachRouteImport } from './routes/_authenticated/career-coach'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedResumeBuilderRouteImport } from './routes/_authenticated/resume-builder'
import { Route as AuthenticatedResumeScannerRouteImport } from './routes/_authenticated/resume-scanner'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CheckoutPlanRouteImport } from './routes/checkout/$plan'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CompaniesSlugRouteImport } from './routes/companies/$slug'
import { Route as GoogleCalendarCallbackRouteImport } from './routes/google-calendar/callback'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as AuthenticatedAiFeatureSlugRouteImport } from './routes/_authenticated/ai/$featureSlug'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer/index'
import { Route as AuthenticatedEmployerCompanyRouteImport } from './routes/_authenticated/employer/company'
import { Route as AuthenticatedEmployerInterviewsRouteImport } from './routes/_authenticated/employer/interviews'
import { Route as AuthenticatedEmployerAiFeatureSlugRouteImport } from './routes/_authenticated/employer/ai/$featureSlug'
import { Route as AuthenticatedEmployerJobsJobIdRouteImport } from './routes/_authenticated/employer/jobs/$jobId'
import { Route as AuthenticatedEmployerJobsNewRouteImport } from './routes/_authenticated/employer/jobs/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailureRoute = PaymentFailureRouteImport.update({
  id: '/payment-failure',
  path: '/payment-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlogEditorRoute = AuthenticatedBlogEditorRouteImport.update({
  id: '/blog-editor',
  path: '/blog-editor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCareerRoute = AuthenticatedCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCareerCoachRoute =
  AuthenticatedCareerCoachRouteImport.update({
    id: '/career-coach',
    path: '/career-coach',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResumeBuilderRoute =
  AuthenticatedResumeBuilderRouteImport.update({
    id: '/resume-builder',
    path: '/resume-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumeScannerRoute =
  AuthenticatedResumeScannerRouteImport.update({
    id: '/resume-scanner',
    path: '/resume-scanner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanRoute = CheckoutPlanRouteImport.update({
  id: '/checkout/$plan',
  path: '/checkout/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleCalendarCallbackRoute = GoogleCalendarCallbackRouteImport.update({
  id: '/google-calendar/callback',
  path: '/google-calendar/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiFeatureSlugRoute =
  AuthenticatedAiFeatureSlugRouteImport.update({
    id: '/ai/$featureSlug',
    path: '/ai/$featureSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerCompanyRoute =
  AuthenticatedEmployerCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerInterviewsRoute =
  AuthenticatedEmployerInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerAiFeatureSlugRoute =
  AuthenticatedEmployerAiFeatureSlugRouteImport.update({
    id: '/ai/$featureSlug',
    path: '/ai/$featureSlug',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerJobsJobIdRoute =
  AuthenticatedEmployerJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerJobsNewRoute =
  AuthenticatedEmployerJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/payment-failure': typeof PaymentFailureRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/blog-editor': typeof AuthenticatedBlogEditorRoute
  '/career': typeof AuthenticatedCareerRoute
  '/career-coach': typeof AuthenticatedCareerCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/resume-builder': typeof AuthenticatedResumeBuilderRoute
  '/resume-scanner': typeof AuthenticatedResumeScannerRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$plan': typeof CheckoutPlanRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/google-calendar/callback': typeof GoogleCalendarCallbackRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/blog/': typeof BlogIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/ai/$featureSlug': typeof AuthenticatedAiFeatureSlugRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/interviews': typeof AuthenticatedEmployerInterviewsRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
  '/employer/ai/$featureSlug': typeof AuthenticatedEmployerAiFeatureSlugRoute
  '/employer/jobs/$jobId': typeof AuthenticatedEmployerJobsJobIdRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/payment-failure': typeof PaymentFailureRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/blog-editor': typeof AuthenticatedBlogEditorRoute
  '/career': typeof AuthenticatedCareerRoute
  '/career-coach': typeof AuthenticatedCareerCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/resume-builder': typeof AuthenticatedResumeBuilderRoute
  '/resume-scanner': typeof AuthenticatedResumeScannerRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$plan': typeof CheckoutPlanRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/google-calendar/callback': typeof GoogleCalendarCallbackRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/blog': typeof BlogIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/ai/$featureSlug': typeof AuthenticatedAiFeatureSlugRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/interviews': typeof AuthenticatedEmployerInterviewsRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
  '/employer/ai/$featureSlug': typeof AuthenticatedEmployerAiFeatureSlugRoute
  '/employer/jobs/$jobId': typeof AuthenticatedEmployerJobsJobIdRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/payment-failure': typeof PaymentFailureRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/blog-editor': typeof AuthenticatedBlogEditorRoute
  '/_authenticated/career': typeof AuthenticatedCareerRoute
  '/_authenticated/career-coach': typeof AuthenticatedCareerCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/resume-builder': typeof AuthenticatedResumeBuilderRoute
  '/_authenticated/resume-scanner': typeof AuthenticatedResumeScannerRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$plan': typeof CheckoutPlanRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/google-calendar/callback': typeof GoogleCalendarCallbackRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/blog/': typeof BlogIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/ai/$featureSlug': typeof AuthenticatedAiFeatureSlugRoute
  '/_authenticated/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/_authenticated/employer/interviews': typeof AuthenticatedEmployerInterviewsRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
  '/_authenticated/employer/ai/$featureSlug': typeof AuthenticatedEmployerAiFeatureSlugRoute
  '/_authenticated/employer/jobs/$jobId': typeof AuthenticatedEmployerJobsJobIdRoute
  '/_authenticated/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/payment-failure'
    | '/payment-success'
    | '/pricing'
    | '/reset-password'
    | '/support'
    | '/admin'
    | '/ai-assistant'
    | '/applications'
    | '/assessments'
    | '/blog-editor'
    | '/career'
    | '/career-coach'
    | '/dashboard'
    | '/employer'
    | '/feed'
    | '/interviews'
    | '/learn'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/referrals'
    | '/resume-builder'
    | '/resume-scanner'
    | '/saved'
    | '/blog/$slug'
    | '/checkout/$plan'
    | '/companies/$slug'
    | '/google-calendar/callback'
    | '/jobs/$jobId'
    | '/blog/'
    | '/companies/'
    | '/jobs/'
    | '/ai/$featureSlug'
    | '/employer/company'
    | '/employer/interviews'
    | '/employer/'
    | '/employer/ai/$featureSlug'
    | '/employer/jobs/$jobId'
    | '/employer/jobs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/payment-failure'
    | '/payment-success'
    | '/pricing'
    | '/reset-password'
    | '/support'
    | '/admin'
    | '/ai-assistant'
    | '/applications'
    | '/assessments'
    | '/blog-editor'
    | '/career'
    | '/career-coach'
    | '/dashboard'
    | '/feed'
    | '/interviews'
    | '/learn'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/referrals'
    | '/resume-builder'
    | '/resume-scanner'
    | '/saved'
    | '/blog/$slug'
    | '/checkout/$plan'
    | '/companies/$slug'
    | '/google-calendar/callback'
    | '/jobs/$jobId'
    | '/blog'
    | '/companies'
    | '/jobs'
    | '/ai/$featureSlug'
    | '/employer/company'
    | '/employer/interviews'
    | '/employer'
    | '/employer/ai/$featureSlug'
    | '/employer/jobs/$jobId'
    | '/employer/jobs/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/payment-failure'
    | '/payment-success'
    | '/pricing'
    | '/reset-password'
    | '/support'
    | '/_authenticated/admin'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/applications'
    | '/_authenticated/assessments'
    | '/_authenticated/blog-editor'
    | '/_authenticated/career'
    | '/_authenticated/career-coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/employer'
    | '/_authenticated/feed'
    | '/_authenticated/interviews'
    | '/_authenticated/learn'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/resume-builder'
    | '/_authenticated/resume-scanner'
    | '/_authenticated/saved'
    | '/blog/$slug'
    | '/checkout/$plan'
    | '/companies/$slug'
    | '/google-calendar/callback'
    | '/jobs/$jobId'
    | '/blog/'
    | '/companies/'
    | '/jobs/'
    | '/_authenticated/ai/$featureSlug'
    | '/_authenticated/employer/company'
    | '/_authenticated/employer/interviews'
    | '/_authenticated/employer/'
    | '/_authenticated/employer/ai/$featureSlug'
    | '/_authenticated/employer/jobs/$jobId'
    | '/_authenticated/employer/jobs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PaymentFailureRoute: typeof PaymentFailureRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutPlanRoute: typeof CheckoutPlanRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  GoogleCalendarCallbackRoute: typeof GoogleCalendarCallbackRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failure': {
      id: '/payment-failure'
      path: '/payment-failure'
      fullPath: '/payment-failure'
      preLoaderRoute: typeof PaymentFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blog-editor': {
      id: '/_authenticated/blog-editor'
      path: '/blog-editor'
      fullPath: '/blog-editor'
      preLoaderRoute: typeof AuthenticatedBlogEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/career': {
      id: '/_authenticated/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AuthenticatedCareerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/career-coach': {
      id: '/_authenticated/career-coach'
      path: '/career-coach'
      fullPath: '/career-coach'
      preLoaderRoute: typeof AuthenticatedCareerCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume-builder': {
      id: '/_authenticated/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof AuthenticatedResumeBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume-scanner': {
      id: '/_authenticated/resume-scanner'
      path: '/resume-scanner'
      fullPath: '/resume-scanner'
      preLoaderRoute: typeof AuthenticatedResumeScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$plan': {
      id: '/checkout/$plan'
      path: '/checkout/$plan'
      fullPath: '/checkout/$plan'
      preLoaderRoute: typeof CheckoutPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-calendar/callback': {
      id: '/google-calendar/callback'
      path: '/google-calendar/callback'
      fullPath: '/google-calendar/callback'
      preLoaderRoute: typeof GoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai/$featureSlug': {
      id: '/_authenticated/ai/$featureSlug'
      path: '/ai/$featureSlug'
      fullPath: '/ai/$featureSlug'
      preLoaderRoute: typeof AuthenticatedAiFeatureSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/company': {
      id: '/_authenticated/employer/company'
      path: '/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof AuthenticatedEmployerCompanyRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/interviews': {
      id: '/_authenticated/employer/interviews'
      path: '/interviews'
      fullPath: '/employer/interviews'
      preLoaderRoute: typeof AuthenticatedEmployerInterviewsRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/ai/$featureSlug': {
      id: '/_authenticated/employer/ai/$featureSlug'
      path: '/ai/$featureSlug'
      fullPath: '/employer/ai/$featureSlug'
      preLoaderRoute: typeof AuthenticatedEmployerAiFeatureSlugRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/jobs/$jobId': {
      id: '/_authenticated/employer/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/employer/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedEmployerJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/jobs/new': {
      id: '/_authenticated/employer/jobs/new'
      path: '/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof AuthenticatedEmployerJobsNewRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
  }
}

interface AuthenticatedEmployerRouteChildren {
  AuthenticatedEmployerCompanyRoute: typeof AuthenticatedEmployerCompanyRoute
  AuthenticatedEmployerInterviewsRoute: typeof AuthenticatedEmployerInterviewsRoute
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
  AuthenticatedEmployerAiFeatureSlugRoute: typeof AuthenticatedEmployerAiFeatureSlugRoute
  AuthenticatedEmployerJobsJobIdRoute: typeof AuthenticatedEmployerJobsJobIdRoute
  AuthenticatedEmployerJobsNewRoute: typeof AuthenticatedEmployerJobsNewRoute
}

const AuthenticatedEmployerRouteChildren: AuthenticatedEmployerRouteChildren = {
  AuthenticatedEmployerCompanyRoute: AuthenticatedEmployerCompanyRoute,
  AuthenticatedEmployerInterviewsRoute: AuthenticatedEmployerInterviewsRoute,
  AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
  AuthenticatedEmployerAiFeatureSlugRoute:
    AuthenticatedEmployerAiFeatureSlugRoute,
  AuthenticatedEmployerJobsJobIdRoute: AuthenticatedEmployerJobsJobIdRoute,
  AuthenticatedEmployerJobsNewRoute: AuthenticatedEmployerJobsNewRoute,
}

const AuthenticatedEmployerRouteWithChildren =
  AuthenticatedEmployerRoute._addFileChildren(
    AuthenticatedEmployerRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedBlogEditorRoute: typeof AuthenticatedBlogEditorRoute
  AuthenticatedCareerRoute: typeof AuthenticatedCareerRoute
  AuthenticatedCareerCoachRoute: typeof AuthenticatedCareerCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRouteWithChildren
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedResumeBuilderRoute: typeof AuthenticatedResumeBuilderRoute
  AuthenticatedResumeScannerRoute: typeof AuthenticatedResumeScannerRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedAiFeatureSlugRoute: typeof AuthenticatedAiFeatureSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedBlogEditorRoute: AuthenticatedBlogEditorRoute,
  AuthenticatedCareerRoute: AuthenticatedCareerRoute,
  AuthenticatedCareerCoachRoute: AuthenticatedCareerCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployerRoute: AuthenticatedEmployerRouteWithChildren,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedResumeBuilderRoute: AuthenticatedResumeBuilderRoute,
  AuthenticatedResumeScannerRoute: AuthenticatedResumeScannerRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedAiFeatureSlugRoute: AuthenticatedAiFeatureSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PaymentFailureRoute: PaymentFailureRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutPlanRoute: CheckoutPlanRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  GoogleCalendarCallbackRoute: GoogleCalendarCallbackRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
